{
 "title": "NBomber",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "test_suite",
    "label": "test suite",
    "query": "SHOW TAG VALUES with KEY = \"test_suite\""
   },
   {
    "name": "test_name",
    "label": "test name",
    "query": "SHOW TAG VALUES with KEY = \"test_name\" WHERE test_suite =~ /^$test_suite$/"
   },
   {
    "name": "scenario",
    "label": "scenario",
    "query": "SHOW TAG VALUES with KEY = \"scenario\" WHERE test_suite =~ /^$test_suite$/ AND test_name =~ /^$test_name$/"
   },
   {
    "name": "step",
    "label": "step",
    "query": "SHOW TAG VALUES with KEY = \"step\" WHERE test_suite =~ /^$test_suite$/ AND test_name =~ /^$test_name$/ AND scenario =~ /^$scenario$/"
   },
   {
    "name": "time_interval",
    "label": "time interval",
    "query": "1s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "$scenario", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "scenario" },
  {
   "title": "Requests Number",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "OK",
     "measurement": "nbomber",
     "query": "SELECT \"ok.request.count\" FROM \"nbomber\" WHERE (\"test_suite\" =~ /^$test_suite$/ AND \"test_name\" =~ /^$test_name$/ AND \"scenario\" =~ /^$scenario$/ AND \"step\" =~ /^$step$/ AND \"operation\" = 'complete') AND $timeFilter",
     "select": [
      [
       { "params": [ "ok.request.count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "test_suite", "operator": "=~", "value": "/^$test_suite$/" },
      { "condition": "AND", "key": "test_name", "operator": "=~", "value": "/^$test_name$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" },
      { "condition": "AND", "key": "step", "operator": "=~", "value": "/^$step$/" },
      { "condition": "AND", "key": "operation", "operator": "=", "value": "complete" }
     ]
    },
    {
     "alias": "FAIL",
     "measurement": "nbomber",
     "query": "SELECT \"ok.request.count\" FROM \"nbomber\" WHERE (\"test_suite\" =~ /^$test_suite$/ AND \"test_name\" =~ /^$test_name$/ AND \"scenario\" =~ /^$scenario$/ AND \"step\" =~ /^$step$/ AND \"operation\" = 'complete') AND $timeFilter",
     "select": [
      [
       { "params": [ "fail.request.count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "test_suite", "operator": "=~", "value": "/^$test_suite$/" },
      { "condition": "AND", "key": "test_name", "operator": "=~", "value": "/^$test_name$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" },
      { "condition": "AND", "key": "step", "operator": "=~", "value": "/^$step$/" },
      { "condition": "AND", "key": "operation", "operator": "=", "value": "complete" }
     ]
    }
   ]
  },
  {
   "title": "Latency Indicators",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "t <= 800",
     "measurement": "nbomber",
     "query": "SELECT last(\"latency_count.less_or_eq_800\") FROM \"nbomber\" WHERE (\"test_suite\" =~ /^$test_suite$/ AND \"test_name\" =~ /^$test_name$/ AND \"scenario\" =~ /^$scenario$/ AND \"operation\" = 'complete') AND $timeFilter",
     "select": [
      [
       { "params": [ "latency_count.less_or_eq_800" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "test_suite", "operator": "=~", "value": "/^$test_suite$/" },
      { "condition": "AND", "key": "test_name", "operator": "=~", "value": "/^$test_name$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" },
      { "condition": "AND", "key": "step", "operator": "=~", "value": "/^$step$/" },
      { "condition": "AND", "key": "operation", "operator": "=", "value": "complete" }
     ]
    },
    {
     "alias": "t > 800 and t < 1200",
     "measurement": "nbomber",
     "query": "SELECT last(\"latency_count.more_800_less_1200\") FROM \"nbomber\" WHERE (\"test_suite\" =~ /^$test_suite$/ AND \"test_name\" =~ /^$test_name$/ AND \"scenario\" =~ /^$scenario$/ AND \"operation\" = 'complete') AND $timeFilter",
     "select": [
      [
       {
        "params": [
         "latency_count.more_800_less_1200"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "test_suite", "operator": "=~", "value": "/^$test_suite$/" },
      { "condition": "AND", "key": "test_name", "operator": "=~", "value": "/^$test_name$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" },
      { "condition": "AND", "key": "step", "operator": "=~", "value": "/^$step$/" },
      { "condition": "AND", "key": "operation", "operator": "=", "value": "complete" }
     ]
    },
    {
     "alias": "t >= 1200",
     "measurement": "nbomber",
     "query": "SELECT last(\"latency_count.more_800_less_1200\") FROM \"nbomber\" WHERE (\"test_suite\" =~ /^$test_suite$/ AND \"test_name\" =~ /^$test_name$/ AND \"scenario\" =~ /^$scenario$/ AND \"operation\" = 'complete') AND $timeFilter",
     "select": [
      [
       { "params": [ "latency_count.more_or_eq_1200" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "test_suite", "operator": "=~", "value": "/^$test_suite$/" },
      { "condition": "AND", "key": "test_name", "operator": "=~", "value": "/^$test_name$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" },
      { "condition": "AND", "key": "step", "operator": "=~", "value": "/^$step$/" },
      { "condition": "AND", "key": "operation", "operator": "=", "value": "complete" }
     ]
    }
   ]
  },
  {
   "title": "Status Codes",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "status_code" ], "type": "tag" }
     ],
     "measurement": "nbomber",
     "query": "SELECT \"status_code.count\" AS \"count\", \"status_code.is_error\" AS \"is error\" FROM \"nbomber\" WHERE (\"test_suite\" =~ /^$test_suite$/ AND \"test_name\" =~ /^$test_name$/ AND \"scenario\" =~ /^$scenario$/ AND \"operation\" = 'complete') AND $timeFilter GROUP BY \"status_code\"",
     "select": [
      [
       { "params": [ "status_code.count" ], "type": "field" }
      ],
      [
       { "params": [ "status_code.is_error" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "test_suite", "operator": "=~", "value": "/^$test_suite$/" },
      { "condition": "AND", "key": "test_name", "operator": "=~", "value": "/^$test_name$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" },
      { "condition": "AND", "key": "step", "operator": "=~", "value": "/^$step$/" },
      { "condition": "AND", "key": "operation", "operator": "=", "value": "complete" }
     ]
    }
   ]
  },
  {
   "title": "OK Stats ($step)",
   "type": "table",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 7 },
   "repeat": "step",
   "targets": [
    {
     "alias": "request count",
     "measurement": "nbomber",
     "query": "SELECT last(\"ok.request.rps\") FROM \"nbomber\" WHERE (\"test_suite\" =~ /^$test_suite$/ AND \"test_name\" =~ /^$test_name$/ AND \"scenario\" =~ /^$scenario$/ AND \"step\" =~ /^$step$/ AND \"operation\" = 'complete') AND $timeFilter",
     "select": [
      [
       { "params": [ "ok.request.count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "test_suite", "operator": "=~", "value": "/^$test_suite$/" },
      { "condition": "AND", "key": "test_name", "operator": "=~", "value": "/^$test_name$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" },
      { "condition": "AND", "key": "step", "operator": "=~", "value": "/^$step$/" },
      { "condition": "AND", "key": "operation", "operator": "=", "value": "complete" }
     ]
    },
    {
     "alias": "RPS",
     "measurement": "nbomber",
     "query": "SELECT last(\"ok.latency.min\") FROM \"nbomber\" WHERE (\"test_suite\" =~ /^$test_suite$/ AND \"test_name\" =~ /^$test_name$/ AND \"scenario\" =~ /^$scenario$/ AND \"step\" =~ /^$step$/ AND \"operation\" = 'complete') AND $timeFilter",
     "select": [
      [
       { "params": [ "ok.request.rps" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "test_suite", "operator": "=~", "value": "/^$test_suite$/" },
      { "condition": "AND", "key": "test_name", "operator": "=~", "value": "/^$test_name$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" },
      { "condition": "AND", "key": "step", "operator": "=~", "value": "/^$step$/" },
      { "condition": "AND", "key": "operation", "operator": "=", "value": "complete" }
     ]
    },
    {
     "alias": "min",
     "measurement": "nbomber",
     "query": "SELECT last(\"ok.latency.min\") FROM \"nbomber\" WHERE (\"test_suite\" =~ /^$test_suite$/ AND \"test_name\" =~ /^$test_name$/ AND \"scenario\" =~ /^$scenario$/ AND \"step\" =~ /^$step$/ AND \"operation\" = 'complete') AND $timeFilter",
     "select": [
      [
       { "params": [ "ok.latency.min" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "test_suite", "operator": "=~", "value": "/^$test_suite$/" },
      { "condition": "AND", "key": "test_name", "operator": "=~", "value": "/^$test_name$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" },
      { "condition": "AND", "key": "step", "operator": "=~", "value": "/^$step$/" },
      { "condition": "AND", "key": "operation", "operator": "=", "value": "complete" }
     ]
    },
    {
     "alias": "mean",
     "measurement": "nbomber",
     "query": "SELECT last(\"ok.latency.min\") FROM \"nbomber\" WHERE (\"test_suite\" =~ /^$test_suite$/ AND \"test_name\" =~ /^$test_name$/ AND \"scenario\" =~ /^$scenario$/ AND \"step\" =~ /^$step$/ AND \"operation\" = 'complete') AND $timeFilter",
     "select": [
      [
       { "params": [ "ok.latency.mean" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "test_suite", "operator": "=~", "value": "/^$test_suite$/" },
      { "condition": "AND", "key": "test_name", "operator": "=~", "value": "/^$test_name$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" },
      { "condition": "AND", "key": "step", "operator": "=~", "value": "/^$step$/" },
      { "condition": "AND", "key": "operation", "operator": "=", "value": "complete" }
     ]
    },
    {
     "alias": "max",
     "measurement": "nbomber",
     "query": "SELECT last(\"ok.latency.min\") FROM \"nbomber\" WHERE (\"test_suite\" =~ /^$test_suite$/ AND \"test_name\" =~ /^$test_name$/ AND \"scenario\" =~ /^$scenario$/ AND \"step\" =~ /^$step$/ AND \"operation\" = 'complete') AND $timeFilter",
     "select": [
      [
       { "params": [ "ok.latency.max" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "test_suite", "operator": "=~", "value": "/^$test_suite$/" },
      { "condition": "AND", "key": "test_name", "operator": "=~", "value": "/^$test_name$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" },
      { "condition": "AND", "key": "step", "operator": "=~", "value": "/^$step$/" },
      { "condition": "AND", "key": "operation", "operator": "=", "value": "complete" }
     ]
    },
    {
     "alias": "50%",
     "measurement": "nbomber",
     "query": "SELECT last(\"ok.latency.min\") FROM \"nbomber\" WHERE (\"test_suite\" =~ /^$test_suite$/ AND \"test_name\" =~ /^$test_name$/ AND \"scenario\" =~ /^$scenario$/ AND \"step\" =~ /^$step$/ AND \"operation\" = 'complete') AND $timeFilter",
     "select": [
      [
       { "params": [ "ok.latency.percent50" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "test_suite", "operator": "=~", "value": "/^$test_suite$/" },
      { "condition": "AND", "key": "test_name", "operator": "=~", "value": "/^$test_name$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" },
      { "condition": "AND", "key": "step", "operator": "=~", "value": "/^$step$/" },
      { "condition": "AND", "key": "operation", "operator": "=", "value": "complete" }
     ]
    },
    {
     "alias": "75%",
     "measurement": "nbomber",
     "query": "SELECT last(\"ok.latency.min\") FROM \"nbomber\" WHERE (\"test_suite\" =~ /^$test_suite$/ AND \"test_name\" =~ /^$test_name$/ AND \"scenario\" =~ /^$scenario$/ AND \"step\" =~ /^$step$/ AND \"operation\" = 'complete') AND $timeFilter",
     "select": [
      [
       { "params": [ "ok.latency.percent75" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "test_suite", "operator": "=~", "value": "/^$test_suite$/" },
      { "condition": "AND", "key": "test_name", "operator": "=~", "value": "/^$test_name$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" },
      { "condition": "AND", "key": "step", "operator": "=~", "value": "/^$step$/" },
      { "condition": "AND", "key": "operation", "operator": "=", "value": "complete" }
     ]
    },
    {
     "alias": "95%",
     "measurement": "nbomber",
     "query": "SELECT last(\"ok.latency.min\") FROM \"nbomber\" WHERE (\"test_suite\" =~ /^$test_suite$/ AND \"test_name\" =~ /^$test_name$/ AND \"scenario\" =~ /^$scenario$/ AND \"step\" =~ /^$step$/ AND \"operation\" = 'complete') AND $timeFilter",
     "select": [
      [
       { "params": [ "ok.latency.percent95" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "test_suite", "operator": "=~", "value": "/^$test_suite$/" },
      { "condition": "AND", "key": "test_name", "operator": "=~", "value": "/^$test_name$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" },
      { "condition": "AND", "key": "step", "operator": "=~", "value": "/^$step$/" },
      { "condition": "AND", "key": "operation", "operator": "=", "value": "complete" }
     ]
    },
    {
     "alias": "99%",
     "measurement": "nbomber",
     "query": "SELECT last(\"ok.latency.min\") FROM \"nbomber\" WHERE (\"test_suite\" =~ /^$test_suite$/ AND \"test_name\" =~ /^$test_name$/ AND \"scenario\" =~ /^$scenario$/ AND \"step\" =~ /^$step$/ AND \"operation\" = 'complete') AND $timeFilter",
     "select": [
      [
       { "params": [ "ok.latency.percent99" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "test_suite", "operator": "=~", "value": "/^$test_suite$/" },
      { "condition": "AND", "key": "test_name", "operator": "=~", "value": "/^$test_name$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" },
      { "condition": "AND", "key": "step", "operator": "=~", "value": "/^$step$/" },
      { "condition": "AND", "key": "operation", "operator": "=", "value": "complete" }
     ]
    },
    {
     "alias": "StdDev",
     "measurement": "nbomber",
     "query": "SELECT last(\"ok.latency.min\") FROM \"nbomber\" WHERE (\"test_suite\" =~ /^$test_suite$/ AND \"test_name\" =~ /^$test_name$/ AND \"scenario\" =~ /^$scenario$/ AND \"step\" =~ /^$step$/ AND \"operation\" = 'complete') AND $timeFilter",
     "select": [
      [
       { "params": [ "ok.latency.stddev" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "test_suite", "operator": "=~", "value": "/^$test_suite$/" },
      { "condition": "AND", "key": "test_name", "operator": "=~", "value": "/^$test_name$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" },
      { "condition": "AND", "key": "step", "operator": "=~", "value": "/^$step$/" },
      { "condition": "AND", "key": "operation", "operator": "=", "value": "complete" }
     ]
    },
    {
     "alias": "data min",
     "measurement": "nbomber",
     "query": "SELECT last(\"ok.latency.min\") FROM \"nbomber\" WHERE (\"test_suite\" =~ /^$test_suite$/ AND \"test_name\" =~ /^$test_name$/ AND \"scenario\" =~ /^$scenario$/ AND \"step\" =~ /^$step$/ AND \"operation\" = 'complete') AND $timeFilter",
     "select": [
      [
       { "params": [ "ok.datatransfer.min" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "test_suite", "operator": "=~", "value": "/^$test_suite$/" },
      { "condition": "AND", "key": "test_name", "operator": "=~", "value": "/^$test_name$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" },
      { "condition": "AND", "key": "step", "operator": "=~", "value": "/^$step$/" },
      { "condition": "AND", "key": "operation", "operator": "=", "value": "complete" }
     ]
    },
    {
     "alias": "data mean",
     "measurement": "nbomber",
     "query": "SELECT last(\"ok.latency.min\") FROM \"nbomber\" WHERE (\"test_suite\" =~ /^$test_suite$/ AND \"test_name\" =~ /^$test_name$/ AND \"scenario\" =~ /^$scenario$/ AND \"step\" =~ /^$step$/ AND \"operation\" = 'complete') AND $timeFilter",
     "select": [
      [
       { "params": [ "ok.datatransfer.mean" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "test_suite", "operator": "=~", "value": "/^$test_suite$/" },
      { "condition": "AND", "key": "test_name", "operator": "=~", "value": "/^$test_name$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" },
      { "condition": "AND", "key": "step", "operator": "=~", "value": "/^$step$/" },
      { "condition": "AND", "key": "operation", "operator": "=", "value": "complete" }
     ]
    },
    {
     "alias": "data max",
     "measurement": "nbomber",
     "query": "SELECT last(\"ok.latency.min\") FROM \"nbomber\" WHERE (\"test_suite\" =~ /^$test_suite$/ AND \"test_name\" =~ /^$test_name$/ AND \"scenario\" =~ /^$scenario$/ AND \"step\" =~ /^$step$/ AND \"operation\" = 'complete') AND $timeFilter",
     "select": [
      [
       { "params": [ "ok.datatransfer.max" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "test_suite", "operator": "=~", "value": "/^$test_suite$/" },
      { "condition": "AND", "key": "test_name", "operator": "=~", "value": "/^$test_name$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" },
      { "condition": "AND", "key": "step", "operator": "=~", "value": "/^$step$/" },
      { "condition": "AND", "key": "operation", "operator": "=", "value": "complete" }
     ]
    },
    {
     "alias": "data all",
     "measurement": "nbomber",
     "query": "SELECT last(\"ok.datatransfer.percent95\") FROM \"nbomber\" WHERE (\"test_suite\" =~ /^$test_suite$/ AND \"test_name\" =~ /^$test_name$/ AND \"scenario\" =~ /^$scenario$/ AND \"step\" =~ /^$step$/ AND \"operation\" = 'complete') AND $timeFilter",
     "select": [
      [
       { "params": [ "ok.datatransfer.all" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "test_suite", "operator": "=~", "value": "/^$test_suite$/" },
      { "condition": "AND", "key": "test_name", "operator": "=~", "value": "/^$test_name$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" },
      { "condition": "AND", "key": "step", "operator": "=~", "value": "/^$step$/" },
      { "condition": "AND", "key": "operation", "operator": "=", "value": "complete" }
     ]
    }
   ]
  },
  {
   "title": "FAIL Stats ($step)",
   "type": "table",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 11 },
   "repeat": "step",
   "targets": [
    {
     "alias": "request count",
     "measurement": "nbomber",
     "query": "SELECT last(\"fail.request.count\") FROM \"nbomber\" WHERE (\"test_suite\" =~ /^$test_suite$/ AND \"test_name\" =~ /^$test_name$/ AND \"scenario\" =~ /^$scenario$/ AND \"step\" =~ /^$step$/ AND \"operation\" = 'complete') AND $timeFilter",
     "select": [
      [
       { "params": [ "ok.request.count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "test_suite", "operator": "=~", "value": "/^$test_suite$/" },
      { "condition": "AND", "key": "test_name", "operator": "=~", "value": "/^$test_name$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" },
      { "condition": "AND", "key": "step", "operator": "=~", "value": "/^$step$/" },
      { "condition": "AND", "key": "operation", "operator": "=", "value": "complete" }
     ]
    },
    {
     "alias": "RPS",
     "measurement": "nbomber",
     "query": "SELECT last(\"fail.request.rps\") FROM \"nbomber\" WHERE (\"test_suite\" =~ /^$test_suite$/ AND \"test_name\" =~ /^$test_name$/ AND \"scenario\" =~ /^$scenario$/ AND \"step\" =~ /^$step$/ AND \"operation\" = 'complete') AND $timeFilter",
     "select": [
      [
       { "params": [ "ok.request.rps" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "test_suite", "operator": "=~", "value": "/^$test_suite$/" },
      { "condition": "AND", "key": "test_name", "operator": "=~", "value": "/^$test_name$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" },
      { "condition": "AND", "key": "step", "operator": "=~", "value": "/^$step$/" },
      { "condition": "AND", "key": "operation", "operator": "=", "value": "complete" }
     ]
    },
    {
     "alias": "min",
     "measurement": "nbomber",
     "query": "SELECT last(\"fail.latency.min\") FROM \"nbomber\" WHERE (\"test_suite\" =~ /^$test_suite$/ AND \"test_name\" =~ /^$test_name$/ AND \"scenario\" =~ /^$scenario$/ AND \"step\" =~ /^$step$/ AND \"operation\" = 'complete') AND $timeFilter",
     "select": [
      [
       { "params": [ "ok.latency.min" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "test_suite", "operator": "=~", "value": "/^$test_suite$/" },
      { "condition": "AND", "key": "test_name", "operator": "=~", "value": "/^$test_name$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" },
      { "condition": "AND", "key": "step", "operator": "=~", "value": "/^$step$/" },
      { "condition": "AND", "key": "operation", "operator": "=", "value": "complete" }
     ]
    },
    {
     "alias": "mean",
     "measurement": "nbomber",
     "query": "SELECT last(\"fail.latency.mean\") FROM \"nbomber\" WHERE (\"test_suite\" =~ /^$test_suite$/ AND \"test_name\" =~ /^$test_name$/ AND \"scenario\" =~ /^$scenario$/ AND \"step\" =~ /^$step$/ AND \"operation\" = 'complete') AND $timeFilter",
     "select": [
      [
       { "params": [ "ok.latency.mean" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "test_suite", "operator": "=~", "value": "/^$test_suite$/" },
      { "condition": "AND", "key": "test_name", "operator": "=~", "value": "/^$test_name$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" },
      { "condition": "AND", "key": "step", "operator": "=~", "value": "/^$step$/" },
      { "condition": "AND", "key": "operation", "operator": "=", "value": "complete" }
     ]
    },
    {
     "alias": "max",
     "measurement": "nbomber",
     "query": "SELECT last(\"fail.latency.max\") FROM \"nbomber\" WHERE (\"test_suite\" =~ /^$test_suite$/ AND \"test_name\" =~ /^$test_name$/ AND \"scenario\" =~ /^$scenario$/ AND \"step\" =~ /^$step$/ AND \"operation\" = 'complete') AND $timeFilter",
     "select": [
      [
       { "params": [ "ok.latency.max" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "test_suite", "operator": "=~", "value": "/^$test_suite$/" },
      { "condition": "AND", "key": "test_name", "operator": "=~", "value": "/^$test_name$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" },
      { "condition": "AND", "key": "step", "operator": "=~", "value": "/^$step$/" },
      { "condition": "AND", "key": "operation", "operator": "=", "value": "complete" }
     ]
    },
    {
     "alias": "50%",
     "measurement": "nbomber",
     "query": "SELECT last(\"fail.latency.percent50\") FROM \"nbomber\" WHERE (\"test_suite\" =~ /^$test_suite$/ AND \"test_name\" =~ /^$test_name$/ AND \"scenario\" =~ /^$scenario$/ AND \"step\" =~ /^$step$/ AND \"operation\" = 'complete') AND $timeFilter",
     "select": [
      [
       { "params": [ "ok.latency.percent50" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "test_suite", "operator": "=~", "value": "/^$test_suite$/" },
      { "condition": "AND", "key": "test_name", "operator": "=~", "value": "/^$test_name$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" },
      { "condition": "AND", "key": "step", "operator": "=~", "value": "/^$step$/" },
      { "condition": "AND", "key": "operation", "operator": "=", "value": "complete" }
     ]
    },
    {
     "alias": "75%",
     "measurement": "nbomber",
     "query": "SELECT last(\"fail.latency.percent75\") FROM \"nbomber\" WHERE (\"test_suite\" =~ /^$test_suite$/ AND \"test_name\" =~ /^$test_name$/ AND \"scenario\" =~ /^$scenario$/ AND \"step\" =~ /^$step$/ AND \"operation\" = 'complete') AND $timeFilter",
     "select": [
      [
       { "params": [ "ok.latency.percent75" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "test_suite", "operator": "=~", "value": "/^$test_suite$/" },
      { "condition": "AND", "key": "test_name", "operator": "=~", "value": "/^$test_name$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" },
      { "condition": "AND", "key": "step", "operator": "=~", "value": "/^$step$/" },
      { "condition": "AND", "key": "operation", "operator": "=", "value": "complete" }
     ]
    },
    {
     "alias": "95%",
     "measurement": "nbomber",
     "query": "SELECT last(\"fail.latency.percent95\") FROM \"nbomber\" WHERE (\"test_suite\" =~ /^$test_suite$/ AND \"test_name\" =~ /^$test_name$/ AND \"scenario\" =~ /^$scenario$/ AND \"step\" =~ /^$step$/ AND \"operation\" = 'complete') AND $timeFilter",
     "select": [
      [
       { "params": [ "ok.latency.percent95" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "test_suite", "operator": "=~", "value": "/^$test_suite$/" },
      { "condition": "AND", "key": "test_name", "operator": "=~", "value": "/^$test_name$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" },
      { "condition": "AND", "key": "step", "operator": "=~", "value": "/^$step$/" },
      { "condition": "AND", "key": "operation", "operator": "=", "value": "complete" }
     ]
    },
    {
     "alias": "99%",
     "measurement": "nbomber",
     "query": "SELECT last(\"fail.latency.percent99\") FROM \"nbomber\" WHERE (\"test_suite\" =~ /^$test_suite$/ AND \"test_name\" =~ /^$test_name$/ AND \"scenario\" =~ /^$scenario$/ AND \"step\" =~ /^$step$/ AND \"operation\" = 'complete') AND $timeFilter",
     "select": [
      [
       { "params": [ "ok.latency.percent99" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "test_suite", "operator": "=~", "value": "/^$test_suite$/" },
      { "condition": "AND", "key": "test_name", "operator": "=~", "value": "/^$test_name$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" },
      { "condition": "AND", "key": "step", "operator": "=~", "value": "/^$step$/" },
      { "condition": "AND", "key": "operation", "operator": "=", "value": "complete" }
     ]
    },
    {
     "alias": "StdDev",
     "measurement": "nbomber",
     "query": "SELECT last(\"fail.latency.stddev\") FROM \"nbomber\" WHERE (\"test_suite\" =~ /^$test_suite$/ AND \"test_name\" =~ /^$test_name$/ AND \"scenario\" =~ /^$scenario$/ AND \"step\" =~ /^$step$/ AND \"operation\" = 'complete') AND $timeFilter",
     "select": [
      [
       { "params": [ "ok.latency.stddev" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "test_suite", "operator": "=~", "value": "/^$test_suite$/" },
      { "condition": "AND", "key": "test_name", "operator": "=~", "value": "/^$test_name$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" },
      { "condition": "AND", "key": "step", "operator": "=~", "value": "/^$step$/" },
      { "condition": "AND", "key": "operation", "operator": "=", "value": "complete" }
     ]
    },
    {
     "alias": "data min",
     "measurement": "nbomber",
     "query": "SELECT last(\"fail.datatransfer.min\") FROM \"nbomber\" WHERE (\"test_suite\" =~ /^$test_suite$/ AND \"test_name\" =~ /^$test_name$/ AND \"scenario\" =~ /^$scenario$/ AND \"step\" =~ /^$step$/ AND \"operation\" = 'complete') AND $timeFilter",
     "select": [
      [
       { "params": [ "ok.datatransfer.min" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "test_suite", "operator": "=~", "value": "/^$test_suite$/" },
      { "condition": "AND", "key": "test_name", "operator": "=~", "value": "/^$test_name$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" },
      { "condition": "AND", "key": "step", "operator": "=~", "value": "/^$step$/" },
      { "condition": "AND", "key": "operation", "operator": "=", "value": "complete" }
     ]
    },
    {
     "alias": "data mean",
     "measurement": "nbomber",
     "query": "SELECT last(\"fail.datatransfer.mean\") FROM \"nbomber\" WHERE (\"test_suite\" =~ /^$test_suite$/ AND \"test_name\" =~ /^$test_name$/ AND \"scenario\" =~ /^$scenario$/ AND \"step\" =~ /^$step$/ AND \"operation\" = 'complete') AND $timeFilter",
     "select": [
      [
       { "params": [ "ok.datatransfer.mean" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "test_suite", "operator": "=~", "value": "/^$test_suite$/" },
      { "condition": "AND", "key": "test_name", "operator": "=~", "value": "/^$test_name$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" },
      { "condition": "AND", "key": "step", "operator": "=~", "value": "/^$step$/" },
      { "condition": "AND", "key": "operation", "operator": "=", "value": "complete" }
     ]
    },
    {
     "alias": "data max",
     "measurement": "nbomber",
     "query": "SELECT last(\"fail.datatransfer.max\") FROM \"nbomber\" WHERE (\"test_suite\" =~ /^$test_suite$/ AND \"test_name\" =~ /^$test_name$/ AND \"scenario\" =~ /^$scenario$/ AND \"step\" =~ /^$step$/ AND \"operation\" = 'complete') AND $timeFilter",
     "select": [
      [
       { "params": [ "ok.datatransfer.max" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "test_suite", "operator": "=~", "value": "/^$test_suite$/" },
      { "condition": "AND", "key": "test_name", "operator": "=~", "value": "/^$test_name$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" },
      { "condition": "AND", "key": "step", "operator": "=~", "value": "/^$step$/" },
      { "condition": "AND", "key": "operation", "operator": "=", "value": "complete" }
     ]
    },
    {
     "alias": "data all",
     "measurement": "nbomber",
     "query": "SELECT last(\"fail.datatransfer.all\") FROM \"nbomber\" WHERE (\"test_suite\" =~ /^$test_suite$/ AND \"test_name\" =~ /^$test_name$/ AND \"scenario\" =~ /^$scenario$/ AND \"step\" =~ /^$step$/ AND \"operation\" = 'complete') AND $timeFilter",
     "select": [
      [
       { "params": [ "ok.datatransfer.all" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "test_suite", "operator": "=~", "value": "/^$test_suite$/" },
      { "condition": "AND", "key": "test_name", "operator": "=~", "value": "/^$test_name$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" },
      { "condition": "AND", "key": "step", "operator": "=~", "value": "/^$step$/" },
      { "condition": "AND", "key": "operation", "operator": "=", "value": "complete" }
     ]
    }
   ]
  },
  {
   "title": "Throughput ($step)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
   "repeat": "step",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "ok RPS",
     "groupBy": [
      { "params": [ "$time_interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "nbomber",
     "query": "SELECT \"ok.request.rps\" FROM \"nbomber\" WHERE (\"test_suite\" =~ /^$test_suite$/ AND \"test_name\" =~ /^$test_name$/ AND \"scenario\" =~ /^$scenario$/ AND \"step\" =~ /^$step$/ AND \"operation\" = 'bombing') AND $timeFilter",
     "select": [
      [
       { "params": [ "ok.request.rps" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "test_suite", "operator": "=~", "value": "/^$test_suite$/" },
      { "condition": "AND", "key": "test_name", "operator": "=~", "value": "/^$test_name$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" },
      { "condition": "AND", "key": "step", "operator": "=~", "value": "/^$step$/" },
      { "condition": "AND", "key": "operation", "operator": "=", "value": "bombing" }
     ]
    },
    {
     "alias": "fail RPS",
     "groupBy": [
      { "params": [ "$time_interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "nbomber",
     "query": "SELECT \"fail.request.rps\" FROM \"nbomber\" WHERE (\"test_suite\" =~ /^$test_suite$/ AND \"test_name\" =~ /^$test_name$/ AND \"scenario\" =~ /^$scenario$/ AND \"step\" =~ /^$step$/ AND \"operation\" = 'bombing') AND $timeFilter",
     "select": [
      [
       { "params": [ "fail.request.rps" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "test_suite", "operator": "=~", "value": "/^$test_suite$/" },
      { "condition": "AND", "key": "test_name", "operator": "=~", "value": "/^$test_name$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" },
      { "condition": "AND", "key": "step", "operator": "=~", "value": "/^$step$/" },
      { "condition": "AND", "key": "operation", "operator": "=", "value": "bombing" }
     ]
    },
    {
     "alias": "load simulation",
     "groupBy": [
      { "params": [ "$time_interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "nbomber",
     "query": "SELECT \"simulation.value\" FROM \"nbomber\" WHERE (\"test_suite\" =~ /^$test_suite$/ AND \"test_name\" =~ /^$test_name$/ AND \"scenario\" =~ /^$scenario$/ AND \"step\" =~ /^$step$/ AND \"operation\" = 'bombing') AND $timeFilter",
     "select": [
      [
       { "params": [ "simulation.value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "test_suite", "operator": "=~", "value": "/^$test_suite$/" },
      { "condition": "AND", "key": "test_name", "operator": "=~", "value": "/^$test_name$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" },
      { "condition": "AND", "key": "step", "operator": "=~", "value": "/^$step$/" },
      { "condition": "AND", "key": "operation", "operator": "=", "value": "bombing" }
     ]
    }
   ]
  },
  {
   "title": "OK Data Transfer ($step)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 23 },
   "repeat": "step",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "min",
     "groupBy": [
      { "params": [ "$time_interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "nbomber",
     "query": "SELECT \"value\" FROM \"nbomber__ok.latency.min\" WHERE (\"test_suite\" =~ /^$test_suite$/ AND \"test_name\" =~ /^$test_name$/ AND \"scenario\" =~ /^$scenario$/ AND \"step\" =~ /^$step$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "ok.datatransfer.min" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "test_suite", "operator": "=~", "value": "/^$test_suite$/" },
      { "condition": "AND", "key": "test_name", "operator": "=~", "value": "/^$test_name$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" },
      { "condition": "AND", "key": "step", "operator": "=~", "value": "/^$step$/" },
      { "condition": "AND", "key": "operation", "operator": "=", "value": "bombing" }
     ]
    },
    {
     "alias": "max",
     "groupBy": [
      { "params": [ "$time_interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "nbomber",
     "query": "SELECT \"value\" FROM \"nbomber__ok.latency.max\" WHERE (\"test_suite\" =~ /^$test_suite$/ AND \"test_name\" =~ /^$test_name$/ AND \"scenario\" =~ /^$scenario$/ AND \"step\" =~ /^$step$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "ok.datatransfer.max" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "test_suite", "operator": "=~", "value": "/^$test_suite$/" },
      { "condition": "AND", "key": "test_name", "operator": "=~", "value": "/^$test_name$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" },
      { "condition": "AND", "key": "step", "operator": "=~", "value": "/^$step$/" },
      { "condition": "AND", "key": "operation", "operator": "=", "value": "bombing" }
     ]
    },
    {
     "alias": "mean",
     "groupBy": [
      { "params": [ "$time_interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "nbomber",
     "query": "SELECT \"value\" FROM \"nbomber__ok.latency.mean\" WHERE (\"test_suite\" =~ /^$test_suite$/ AND \"test_name\" =~ /^$test_name$/ AND \"scenario\" =~ /^$scenario$/ AND \"step\" =~ /^$step$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "ok.datatransfer.mean" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "test_suite", "operator": "=~", "value": "/^$test_suite$/" },
      { "condition": "AND", "key": "test_name", "operator": "=~", "value": "/^$test_name$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" },
      { "condition": "AND", "key": "step", "operator": "=~", "value": "/^$step$/" },
      { "condition": "AND", "key": "operation", "operator": "=", "value": "bombing" }
     ]
    },
    {
     "alias": "all",
     "groupBy": [
      { "params": [ "$time_interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "nbomber",
     "query": "SELECT \"value\" FROM \"nbomber__ok.latency.percent50\" WHERE (\"test_suite\" =~ /^$test_suite$/ AND \"test_name\" =~ /^$test_name$/ AND \"scenario\" =~ /^$scenario$/ AND \"step\" =~ /^$step$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "ok.datatransfer.all" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "test_suite", "operator": "=~", "value": "/^$test_suite$/" },
      { "condition": "AND", "key": "test_name", "operator": "=~", "value": "/^$test_name$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" },
      { "condition": "AND", "key": "step", "operator": "=~", "value": "/^$step$/" },
      { "condition": "AND", "key": "operation", "operator": "=", "value": "bombing" }
     ]
    },
    {
     "alias": "50%",
     "groupBy": [
      { "params": [ "$time_interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "nbomber",
     "query": "SELECT \"value\" FROM \"nbomber__ok.latency.percent50\" WHERE (\"test_suite\" =~ /^$test_suite$/ AND \"test_name\" =~ /^$test_name$/ AND \"scenario\" =~ /^$scenario$/ AND \"step\" =~ /^$step$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "ok.datatransfer.percent50" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "test_suite", "operator": "=~", "value": "/^$test_suite$/" },
      { "condition": "AND", "key": "test_name", "operator": "=~", "value": "/^$test_name$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" },
      { "condition": "AND", "key": "step", "operator": "=~", "value": "/^$step$/" },
      { "condition": "AND", "key": "operation", "operator": "=", "value": "bombing" }
     ]
    },
    {
     "alias": "75%",
     "groupBy": [
      { "params": [ "$time_interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "nbomber",
     "query": "SELECT \"value\" FROM \"nbomber__ok.datatransfer.percent75\" WHERE (\"test_suite\" =~ /^$test_suite$/ AND \"test_name\" =~ /^$test_name$/ AND \"scenario\" =~ /^$scenario$/ AND \"step\" =~ /^$step$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "ok.datatransfer.percent75" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "test_suite", "operator": "=~", "value": "/^$test_suite$/" },
      { "condition": "AND", "key": "test_name", "operator": "=~", "value": "/^$test_name$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" },
      { "condition": "AND", "key": "step", "operator": "=~", "value": "/^$step$/" },
      { "condition": "AND", "key": "operation", "operator": "=", "value": "bombing" }
     ]
    },
    {
     "alias": "95%",
     "groupBy": [
      { "params": [ "$time_interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "nbomber",
     "query": "SELECT \"value\" FROM \"nbomber__ok.datatransfer.percent95\" WHERE (\"test_suite\" =~ /^$test_suite$/ AND \"test_name\" =~ /^$test_name$/ AND \"scenario\" =~ /^$scenario$/ AND \"step\" =~ /^$step$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "ok.datatransfer.percent95" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "test_suite", "operator": "=~", "value": "/^$test_suite$/" },
      { "condition": "AND", "key": "test_name", "operator": "=~", "value": "/^$test_name$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" },
      { "condition": "AND", "key": "step", "operator": "=~", "value": "/^$step$/" },
      { "condition": "AND", "key": "operation", "operator": "=", "value": "bombing" }
     ]
    },
    {
     "alias": "99%",
     "groupBy": [
      { "params": [ "$time_interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "nbomber",
     "query": "SELECT \"value\" FROM \"nbomber__ok.datatransfer.percent99\" WHERE (\"test_suite\" =~ /^$test_suite$/ AND \"test_name\" =~ /^$test_name$/ AND \"scenario\" =~ /^$scenario$/ AND \"step\" =~ /^$step$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "ok.datatransfer.percent99" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "test_suite", "operator": "=~", "value": "/^$test_suite$/" },
      { "condition": "AND", "key": "test_name", "operator": "=~", "value": "/^$test_name$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" },
      { "condition": "AND", "key": "step", "operator": "=~", "value": "/^$step$/" },
      { "condition": "AND", "key": "operation", "operator": "=", "value": "bombing" }
     ]
    }
   ]
  },
  {
   "title": "OK Latency ($step)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 31 },
   "repeat": "step",
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "min",
     "groupBy": [
      { "params": [ "$time_interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "nbomber",
     "query": "SELECT \"value\" FROM \"nbomber__ok.latency.min\" WHERE (\"test_suite\" =~ /^$test_suite$/ AND \"test_name\" =~ /^$test_name$/ AND \"scenario\" =~ /^$scenario$/ AND \"step\" =~ /^$step$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "ok.latency.min" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "test_suite", "operator": "=~", "value": "/^$test_suite$/" },
      { "condition": "AND", "key": "test_name", "operator": "=~", "value": "/^$test_name$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" },
      { "condition": "AND", "key": "step", "operator": "=~", "value": "/^$step$/" },
      { "condition": "AND", "key": "operation", "operator": "=", "value": "bombing" }
     ]
    },
    {
     "alias": "max",
     "groupBy": [
      { "params": [ "$time_interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "nbomber",
     "query": "SELECT \"value\" FROM \"nbomber__ok.latency.min\" WHERE (\"test_suite\" =~ /^$test_suite$/ AND \"test_name\" =~ /^$test_name$/ AND \"scenario\" =~ /^$scenario$/ AND \"step\" =~ /^$step$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "ok.latency.max" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "test_suite", "operator": "=~", "value": "/^$test_suite$/" },
      { "condition": "AND", "key": "test_name", "operator": "=~", "value": "/^$test_name$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" },
      { "condition": "AND", "key": "step", "operator": "=~", "value": "/^$step$/" },
      { "condition": "AND", "key": "operation", "operator": "=", "value": "bombing" }
     ]
    },
    {
     "alias": "mean",
     "groupBy": [
      { "params": [ "$time_interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "nbomber",
     "query": "SELECT \"value\" FROM \"nbomber__ok.latency.mean\" WHERE (\"test_suite\" =~ /^$test_suite$/ AND \"test_name\" =~ /^$test_name$/ AND \"scenario\" =~ /^$scenario$/ AND \"step\" =~ /^$step$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "ok.latency.mean" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "test_suite", "operator": "=~", "value": "/^$test_suite$/" },
      { "condition": "AND", "key": "test_name", "operator": "=~", "value": "/^$test_name$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" },
      { "condition": "AND", "key": "step", "operator": "=~", "value": "/^$step$/" },
      { "condition": "AND", "key": "operation", "operator": "=", "value": "bombing" }
     ]
    },
    {
     "alias": "50%",
     "groupBy": [
      { "params": [ "$time_interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "nbomber",
     "query": "SELECT \"value\" FROM \"nbomber__ok.latency.percent50\" WHERE (\"test_suite\" =~ /^$test_suite$/ AND \"test_name\" =~ /^$test_name$/ AND \"scenario\" =~ /^$scenario$/ AND \"step\" =~ /^$step$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "ok.latency.percent50" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "test_suite", "operator": "=~", "value": "/^$test_suite$/" },
      { "condition": "AND", "key": "test_name", "operator": "=~", "value": "/^$test_name$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" },
      { "condition": "AND", "key": "step", "operator": "=~", "value": "/^$step$/" },
      { "condition": "AND", "key": "operation", "operator": "=", "value": "bombing" }
     ]
    },
    {
     "alias": "75%",
     "groupBy": [
      { "params": [ "$time_interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "nbomber",
     "query": "SELECT \"value\" FROM \"nbomber__ok.latency.percent50\" WHERE (\"test_suite\" =~ /^$test_suite$/ AND \"test_name\" =~ /^$test_name$/ AND \"scenario\" =~ /^$scenario$/ AND \"step\" =~ /^$step$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "ok.latency.percent75" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "test_suite", "operator": "=~", "value": "/^$test_suite$/" },
      { "condition": "AND", "key": "test_name", "operator": "=~", "value": "/^$test_name$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" },
      { "condition": "AND", "key": "step", "operator": "=~", "value": "/^$step$/" },
      { "condition": "AND", "key": "operation", "operator": "=", "value": "bombing" }
     ]
    },
    {
     "alias": "95%",
     "groupBy": [
      { "params": [ "$time_interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "nbomber",
     "query": "SELECT \"value\" FROM \"nbomber__ok.latency.percent50\" WHERE (\"test_suite\" =~ /^$test_suite$/ AND \"test_name\" =~ /^$test_name$/ AND \"scenario\" =~ /^$scenario$/ AND \"step\" =~ /^$step$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "ok.latency.percent95" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "test_suite", "operator": "=~", "value": "/^$test_suite$/" },
      { "condition": "AND", "key": "test_name", "operator": "=~", "value": "/^$test_name$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" },
      { "condition": "AND", "key": "step", "operator": "=~", "value": "/^$step$/" },
      { "condition": "AND", "key": "operation", "operator": "=", "value": "bombing" }
     ]
    },
    {
     "alias": "99%",
     "groupBy": [
      { "params": [ "$time_interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "nbomber",
     "query": "SELECT \"value\" FROM \"nbomber__ok.latency.percent99\" WHERE (\"test_suite\" =~ /^$test_suite$/ AND \"test_name\" =~ /^$test_name$/ AND \"scenario\" =~ /^$scenario$/ AND \"step\" =~ /^$step$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "ok.latency.percent99" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "test_suite", "operator": "=~", "value": "/^$test_suite$/" },
      { "condition": "AND", "key": "test_name", "operator": "=~", "value": "/^$test_name$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" },
      { "condition": "AND", "key": "step", "operator": "=~", "value": "/^$step$/" },
      { "condition": "AND", "key": "operation", "operator": "=", "value": "bombing" }
     ]
    }
   ]
  },
  {
   "title": "FAIL Latency ($step)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 39 },
   "repeat": "step",
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "min",
     "groupBy": [
      { "params": [ "$time_interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "nbomber",
     "select": [
      [
       { "params": [ "fail.latency.min" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "test_suite", "operator": "=~", "value": "/^$test_suite$/" },
      { "condition": "AND", "key": "test_name", "operator": "=~", "value": "/^$test_name$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" },
      { "condition": "AND", "key": "step", "operator": "=~", "value": "/^$step$/" },
      { "condition": "AND", "key": "operation", "operator": "=", "value": "bombing" }
     ]
    },
    {
     "alias": "max",
     "groupBy": [
      { "params": [ "$time_interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "nbomber",
     "select": [
      [
       { "params": [ "fail.latency.max" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "test_suite", "operator": "=~", "value": "/^$test_suite$/" },
      { "condition": "AND", "key": "test_name", "operator": "=~", "value": "/^$test_name$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" },
      { "condition": "AND", "key": "step", "operator": "=~", "value": "/^$step$/" },
      { "condition": "AND", "key": "operation", "operator": "=", "value": "bombing" }
     ]
    },
    {
     "alias": "mean",
     "groupBy": [
      { "params": [ "$time_interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "nbomber",
     "select": [
      [
       { "params": [ "fail.latency.mean" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "test_suite", "operator": "=~", "value": "/^$test_suite$/" },
      { "condition": "AND", "key": "test_name", "operator": "=~", "value": "/^$test_name$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" },
      { "condition": "AND", "key": "step", "operator": "=~", "value": "/^$step$/" },
      { "condition": "AND", "key": "operation", "operator": "=", "value": "bombing" }
     ]
    },
    {
     "alias": "50%",
     "groupBy": [
      { "params": [ "$time_interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "nbomber",
     "query": "SELECT \"value\" FROM \"nbomber__fail.latency.mean\" WHERE (\"test_suite\" =~ /^$test_suite$/ AND \"test_name\" =~ /^$test_name$/ AND \"scenario\" =~ /^$scenario$/ AND \"step\" =~ /^$step$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "fail.latency.percent50" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "test_suite", "operator": "=~", "value": "/^$test_suite$/" },
      { "condition": "AND", "key": "test_name", "operator": "=~", "value": "/^$test_name$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" },
      { "condition": "AND", "key": "step", "operator": "=~", "value": "/^$step$/" },
      { "condition": "AND", "key": "operation", "operator": "=", "value": "bombing" }
     ]
    },
    {
     "alias": "75%",
     "groupBy": [
      { "params": [ "$time_interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "nbomber",
     "query": "SELECT \"value\" FROM \"nbomber__fail.latency.percent75\" WHERE (\"test_suite\" =~ /^$test_suite$/ AND \"test_name\" =~ /^$test_name$/ AND \"scenario\" =~ /^$scenario$/ AND \"step\" =~ /^$step$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "fail.latency.percent75" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "test_suite", "operator": "=~", "value": "/^$test_suite$/" },
      { "condition": "AND", "key": "test_name", "operator": "=~", "value": "/^$test_name$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" },
      { "condition": "AND", "key": "step", "operator": "=~", "value": "/^$step$/" },
      { "condition": "AND", "key": "operation", "operator": "=", "value": "bombing" }
     ]
    },
    {
     "alias": "95%",
     "groupBy": [
      { "params": [ "$time_interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "nbomber",
     "query": "SELECT \"fail.latency.percent95\" FROM \"nbomber\" WHERE (\"test_suite\" =~ /^$test_suite$/ AND \"test_name\" =~ /^$test_name$/ AND \"scenario\" =~ /^$scenario$/ AND \"step\" =~ /^$step$/ AND \"operation\" = 'bombing') AND $timeFilter",
     "select": [
      [
       { "params": [ "fail.latency.percent75" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "test_suite", "operator": "=~", "value": "/^$test_suite$/" },
      { "condition": "AND", "key": "test_name", "operator": "=~", "value": "/^$test_name$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" },
      { "condition": "AND", "key": "step", "operator": "=~", "value": "/^$step$/" },
      { "condition": "AND", "key": "operation", "operator": "=", "value": "bombing" }
     ]
    },
    {
     "alias": "99%",
     "groupBy": [
      { "params": [ "$time_interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "nbomber",
     "query": "SELECT \"fail.latency.percent99\" FROM \"nbomber\" WHERE (\"test_suite\" =~ /^$test_suite$/ AND \"test_name\" =~ /^$test_name$/ AND \"scenario\" =~ /^$scenario$/ AND \"step\" =~ /^$step$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "fail.latency.percent99" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "test_suite", "operator": "=~", "value": "/^$test_suite$/" },
      { "condition": "AND", "key": "test_name", "operator": "=~", "value": "/^$test_name$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" },
      { "condition": "AND", "key": "step", "operator": "=~", "value": "/^$step$/" },
      { "condition": "AND", "key": "operation", "operator": "=", "value": "bombing" }
     ]
    }
   ]
  },
  {
   "title": "FAIL Data Transfer ($step)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 47 },
   "repeat": "step",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "min",
     "groupBy": [
      { "params": [ "$time_interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "nbomber",
     "query": "SELECT \"value\" FROM \"nbomber__fail.datatransfer.min\" WHERE (\"test_suite\" =~ /^$test_suite$/ AND \"test_name\" =~ /^$test_name$/ AND \"scenario\" =~ /^$scenario$/ AND \"step\" =~ /^$step$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "fail.datatransfer.min" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "test_suite", "operator": "=~", "value": "/^$test_suite$/" },
      { "condition": "AND", "key": "test_name", "operator": "=~", "value": "/^$test_name$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" },
      { "condition": "AND", "key": "step", "operator": "=~", "value": "/^$step$/" },
      { "condition": "AND", "key": "operation", "operator": "=", "value": "bombing" }
     ]
    },
    {
     "alias": "max",
     "groupBy": [
      { "params": [ "$time_interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "nbomber",
     "query": "SELECT \"value\" FROM \"nbomber__fail.datatransfer.max\" WHERE (\"test_suite\" =~ /^$test_suite$/ AND \"test_name\" =~ /^$test_name$/ AND \"scenario\" =~ /^$scenario$/ AND \"step\" =~ /^$step$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "fail.datatransfer.max" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "test_suite", "operator": "=~", "value": "/^$test_suite$/" },
      { "condition": "AND", "key": "test_name", "operator": "=~", "value": "/^$test_name$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" },
      { "condition": "AND", "key": "step", "operator": "=~", "value": "/^$step$/" },
      { "condition": "AND", "key": "operation", "operator": "=", "value": "bombing" }
     ]
    },
    {
     "alias": "mean",
     "groupBy": [
      { "params": [ "$time_interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "nbomber",
     "query": "SELECT \"value\" FROM \"nbomber__fail.datatransfer.mean\" WHERE (\"test_suite\" =~ /^$test_suite$/ AND \"test_name\" =~ /^$test_name$/ AND \"scenario\" =~ /^$scenario$/ AND \"step\" =~ /^$step$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "fail.datatransfer.mean" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "test_suite", "operator": "=~", "value": "/^$test_suite$/" },
      { "condition": "AND", "key": "test_name", "operator": "=~", "value": "/^$test_name$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" },
      { "condition": "AND", "key": "step", "operator": "=~", "value": "/^$step$/" },
      { "condition": "AND", "key": "operation", "operator": "=", "value": "bombing" }
     ]
    },
    {
     "alias": "all",
     "groupBy": [
      { "params": [ "$time_interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "nbomber",
     "query": "SELECT \"value\" FROM \"nbomber__fail.datatransfer.all\" WHERE (\"test_suite\" =~ /^$test_suite$/ AND \"test_name\" =~ /^$test_name$/ AND \"scenario\" =~ /^$scenario$/ AND \"step\" =~ /^$step$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "fail.datatransfer.all" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "test_suite", "operator": "=~", "value": "/^$test_suite$/" },
      { "condition": "AND", "key": "test_name", "operator": "=~", "value": "/^$test_name$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" },
      { "condition": "AND", "key": "step", "operator": "=~", "value": "/^$step$/" },
      { "condition": "AND", "key": "operation", "operator": "=", "value": "bombing" }
     ]
    },
    {
     "alias": "50%",
     "groupBy": [
      { "params": [ "$time_interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "nbomber",
     "query": "SELECT \"value\" FROM \"nbomber__fail.datatransfer.percent50\" WHERE (\"test_suite\" =~ /^$test_suite$/ AND \"test_name\" =~ /^$test_name$/ AND \"scenario\" =~ /^$scenario$/ AND \"step\" =~ /^$step$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "fail.datatransfer.percent50" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "test_suite", "operator": "=~", "value": "/^$test_suite$/" },
      { "condition": "AND", "key": "test_name", "operator": "=~", "value": "/^$test_name$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" },
      { "condition": "AND", "key": "step", "operator": "=~", "value": "/^$step$/" },
      { "condition": "AND", "key": "operation", "operator": "=", "value": "bombing" }
     ]
    },
    {
     "alias": "75%",
     "groupBy": [
      { "params": [ "$time_interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "nbomber",
     "query": "SELECT \"value\" FROM \"nbomber__fail.datatransfer.percent50\" WHERE (\"test_suite\" =~ /^$test_suite$/ AND \"test_name\" =~ /^$test_name$/ AND \"scenario\" =~ /^$scenario$/ AND \"step\" =~ /^$step$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "fail.datatransfer.percent75" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "test_suite", "operator": "=~", "value": "/^$test_suite$/" },
      { "condition": "AND", "key": "test_name", "operator": "=~", "value": "/^$test_name$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" },
      { "condition": "AND", "key": "step", "operator": "=~", "value": "/^$step$/" },
      { "condition": "AND", "key": "operation", "operator": "=", "value": "bombing" }
     ]
    },
    {
     "alias": "95%",
     "groupBy": [
      { "params": [ "$time_interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "nbomber",
     "query": "SELECT \"value\" FROM \"nbomber__fail.datatransfer.percent95\" WHERE (\"test_suite\" =~ /^$test_suite$/ AND \"test_name\" =~ /^$test_name$/ AND \"scenario\" =~ /^$scenario$/ AND \"step\" =~ /^$step$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "fail.datatransfer.percent95" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "test_suite", "operator": "=~", "value": "/^$test_suite$/" },
      { "condition": "AND", "key": "test_name", "operator": "=~", "value": "/^$test_name$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" },
      { "condition": "AND", "key": "step", "operator": "=~", "value": "/^$step$/" },
      { "condition": "AND", "key": "operation", "operator": "=", "value": "bombing" }
     ]
    },
    {
     "alias": "99%",
     "groupBy": [
      { "params": [ "$time_interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "nbomber",
     "query": "SELECT \"value\" FROM \"nbomber__fail.datatransfer.percent99\" WHERE (\"test_suite\" =~ /^$test_suite$/ AND \"test_name\" =~ /^$test_name$/ AND \"scenario\" =~ /^$scenario$/ AND \"step\" =~ /^$step$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "fail.datatransfer.percent99" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "test_suite", "operator": "=~", "value": "/^$test_suite$/" },
      { "condition": "AND", "key": "test_name", "operator": "=~", "value": "/^$test_name$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" },
      { "condition": "AND", "key": "step", "operator": "=~", "value": "/^$step$/" },
      { "condition": "AND", "key": "operation", "operator": "=", "value": "bombing" }
     ]
    }
   ]
  }
 ]
}